#!/bin/bash

#reportEvent  script to create a report of an event in the pdStressStrain.f 
#              output files.

#  Copyright (C) 2015  Al Conle
# This file is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the license, or (at
# your option) any later version.
#  This  file is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTA-
# BILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#  You should have received a copy of the GNU General PUblic License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place -Suite 330, Boston, MA 02111-1307, USA. Try also their
# web site: http://www.gnu.org/copyleft/gpl.html


#Use "$@" to represent all the arguments:
#for var in "$@"
#do
#    echo "$var"
#done

echo  "#Event $1 end status data is at bottom of this file "    > "event$1.StrSts"
for file in  loops.??
do
# output as a comment:
  grep -H "$1" $file | sed -e "s/loops/#loops/"                >> "event$1.StrSts"
done

for file in loops.??
do
# output for plotting:
  grep -H "$1" $file |tail -1 | sed -e "s/loops.//" -e "s/:/ /" >> "event$1.StrSts"
done

#Create the gnuplot load file
   echo "set term pngcairo size 600,520 font \"Palatino-Bold,14\""  >loadgp6
    echo "set output \"event$1.end.png\" "     >> loadgp6
    echo "set size 1.0,1.0 "                   >> loadgp6
    echo "set multiplot "                      >> loadgp6

    echo "set size 0.98,0.5 "                   >> loadgp6
    echo "set origin 0.02,0.5 "                 >> loadgp6
#    grep \#SEGMENT= >titleOut
    echo "set title \"End of Event $1  \" "     >> loadgp6
    echo "set grid"                             >> loadgp6
#    echo "set xlabel \"Tube Layer Edge No.\" " >> loadgp6
    echo "set yrange [-500:500] "               >> loadgp6
    echo "set ylabel \"Stress, mpa\" "      >> loadgp6

#    echo "set y2range [500:800.] "            >> loadgp6
#    echo "set format y2 \"%f\"  "            >> loadgp6

    echo "set arrow 1 from 1,0 to 11,0 nohead lc rgb \"green\"" >>loadgp6
    echo "plot \"event$1.StrSts\"  u 1:3 w lp  "                >> loadgp6
#    gnuplot "loadgp6"


    echo "set size 1.00,0.5 "                   >> loadgp6
    echo "set origin 0.0,0.0 "                  >> loadgp6

#    echo "unset y2tics "                        >> loadgp6
#    echo "unset y2label "                        >> loadgp6
    echo "unset title "                        >> loadgp6
    echo "set yrange [-0.012:0.012] "           >> loadgp6
    echo "set ylabel \"Strain         \" "      >> loadgp6
    echo "set xlabel \"Tube Layer Edge No.\" "  >> loadgp6

    echo "set arrow 2 from 1,0 to 11,0 nohead lc rgb \"green\"" >>loadgp6
    echo "plot \"event$1.StrSts\" u 1:2 w lp "  >> loadgp6
    gnuplot "loadgp6"

#xv shows an image.  Any other similar utility is fine too.
xv  "event$1.end.png" &

exit

